name: Sync Scripts to Gitee and Update @require

on:
  push:
    branches:
      - main
    workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update @require field for specified scripts (in workspace only)
        run: |
          NEW="// @require      https://gitee.com/zqzhang1996/MWIscript/raw/main/MWI_Toolkit.js"
          for FILE in MWI_Expected_Quantity_Helper.js MWI_Toolkit_Calculator.js; do
            if [ -f "$FILE" ]; then
              sed -i 's|// @require[ ]*https://update\.greasyfork\.org/scripts/[0-9]\+/[0-9]\+/MWI_Toolkit\.js|'"$NEW"'|g' "$FILE"
            fi
          done

      # Do not commit back to GitHub, only push to Gitee mirror

      - name: Push to Gitee mirror (with require replaced)
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git config --global user.name "zqzhang1996"
          git config --global user.email "zqzhang1996@outlook.com"
          git remote add gitee https://zqzhang1996:${GITEE_TOKEN}@gitee.com/zqzhang1996/MWIscript.git
          git add MWI_Expected_Quantity_Helper.js MWI_Toolkit_Calculator.js
          git commit -m "auto: update @require field for Gitee mirror"
          git push -f gitee HEAD:main
